name: Maven compilation and Docker image build

on:
  push:
    branches: [ main, docker-test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Login Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_LOGIN }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v1
          id: buildx
      - name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          id: docker_build
          with:
            context: ./
            file: ./Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: radixhomework/gateway:$(date +%s)
