name: Maven compilation and Docker image build

on:
  push:
    branches: [ main, docker-test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gateway:$(date +%s)
      - name: Push to Dcoker Hub
        run: docker push radixhomework/gateway:tagname
